needle: "\nThe special magic {city} number is: {rnd_number}.\n"
haystack_dir: "PaulGrahamEssays"
retrieval_question: "What is the result of the following math problem? "
results_version: 1
context_lengths_min: 1000
context_lengths_max: 32000
context_lengths_num_intervals: 35
document_depth_percent_min: 0
document_depth_percent_max: 100
document_depth_percent_intervals: 35
model_provider: "OpenAI"
model_name: "gpt-4-turbo-preview"
n_needles_total: 2
needles_dis: 1000
save_prefix: "results/debug"
inject: ""
mode: "math"
url: "YOUR ENDPOINT HERE"
openai_api_key: "YOUR KEY HERE"
